version: '2'
services:
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379

  mariadb:
    image: 'mariadb:latest'
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'